export const requests = [
  {
    id: 1,
    residentName: "Aarav",
    area: "HSR Layout",
    category: "Water Leakage",
    description: "Pipe leakage near Block 2",
    priority: "High",
    status: "Open",
    assignedWorker: "Ramesh",
    createdAt: "2026-06-01",
  },
  {
    id: 2,
    residentName: "Sneha",
    area: "Indiranagar",
    category: "Streetlight Issue",
    description: "Streetlight not working near main road",
    priority: "Medium",
    status: "Assigned",
    assignedWorker: "Suresh",
    createdAt: "2026-06-02",
  },
  {
    id: 3,
    residentName: "Rahul",
    area: "BTM Layout",
    category: "Garbage Pickup",
    description: "Garbage not collected for 2 days",
    priority: "High",
    status: "In Progress",
    assignedWorker: "Mahesh",
    createdAt: "2026-06-02",
  },
  {
    id: 4,
    residentName: "Meera",
    area: "Whitefield",
    category: "Road Damage",
    description: "Potholes causing traffic issue",
    priority: "Low",
    status: "Open",
    assignedWorker: "N/A",
    createdAt: "2026-06-03",
  },
  {
    id: 5,
    residentName: "Vikram",
    area: "Jayanagar",
    category: "Drainage Blockage",
    description: "Drainage overflow near apartment",
    priority: "High",
    status: "Resolved",
    assignedWorker: "Raghu",
    createdAt: "2026-06-04",
  },
  {
    id: 6,
    residentName: "Priya",
    area: "Koramangala",
    category: "Water Leakage",
    description: "Continuous leakage near park",
    priority: "Medium",
    status: "Open",
    assignedWorker: "N/A",
    createdAt: "2026-06-05",
  },
  {
    id: 7,
    residentName: "Kiran",
    area: "Electronic City",
    category: "Garbage Pickup",
    description: "Overflowing bins near gate",
    priority: "Medium",
    status: "Assigned",
    assignedWorker: "Arun",
    createdAt: "2026-06-05",
  },
  {
    id: 8,
    residentName: "Anita",
    area: "Marathahalli",
    category: "Streetlight Issue",
    description: "Entire lane is dark in the evening",
    priority: "High",
    status: "Open",
    assignedWorker: "N/A",
    createdAt: "2026-06-06",
  },
];
